title = 'HackLAB UCM'
baseURL = 'https://jarshvor.github.io/hacklab-ucm'

defaultContentLanguage = 'en'
languageCode = 'en-us'

removePathAccents = true

googleAnalytics = ''

enableGitInfo = true

markup.highlight.noClasses = false

theme = 'docura'

[taxonomies]
  category = 'categories'
  tag = 'tags'
  author = 'authors'
  material = 'materials'
