[en]
contentDir = 'content/en'
languageName = 'English'
weight = 1

[es]
contentDir = 'content/es'
languageName = 'Spanish'
weight = 2
  [es.permalinks]
    [es.permalinks.section]
      docs = '/docs/'
      events = '/eventos/'
      people = '/personas/'
      projects = '/proyectos/'
      research = '/investigacion/'
    [es.permalinks.page]
      docs = '/docs/:slug/'
      events = '/eventos/:slug'
      people = '/personas/:slug'
      projects = '/proyectos/:slug'
      research = '/investigacion/:slug'
